name: live_performer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.2.0
  code_assets: ^1.0.0
  hooks: ^1.0.3
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  ffigen: ^20.1.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
