// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_error>)>()
external void mixer_error_free(ffi.Pointer<mixer_error> error);

@ffi.Native<ffi.Void Function()>()
external void mixer_initialize();

@ffi.Native<ffi.Void Function()>()
external void mixer_shutdown();

@ffi.Native<ffi.Pointer<engine_handle> Function()>()
external ffi.Pointer<engine_handle> mixer_engine_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<engine_handle>)>()
external void mixer_engine_destroy(ffi.Pointer<engine_handle> handle);

@ffi.Native<
  mixer_call_result Function(
    ffi.Pointer<engine_handle>,
    ffi.Pointer<ffi.Pointer<mixer_audio_device_type_array>>,
    ffi.Pointer<mixer_error>,
  )
>()
external int mixer_audio_devices_list(
  ffi.Pointer<engine_handle> handle,
  ffi.Pointer<ffi.Pointer<mixer_audio_device_type_array>> out,
  ffi.Pointer<mixer_error> outError,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_audio_device_type_array>)>()
external void mixer_audio_devices_list_free(
  ffi.Pointer<mixer_audio_device_type_array> reference,
);

typedef mixer_call_result = ffi.Int32;
typedef Dartmixer_call_result = int;
typedef mixer_error = ffi.Pointer<ffi.Char>;

final class engine_handle extends ffi.Opaque {}

final class mixer_audio_device_type extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Size()
  external int device_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> device_names;
}

final class mixer_audio_device_type_array extends ffi.Struct {
  @ffi.Size()
  external int count;

  external ffi.Pointer<ffi.Pointer<mixer_audio_device_type>> device_types;
}

const int MIXER_OK = 0;

const int MIXER_ERROR = 1;

const int MIXER_ERROR_INVALID_HANDLE = 2;
