import 'dart:io';

import 'src/abi_codegen/generators/abi_generator.dart';
import 'src/abi_codegen/input.dart';
import 'src/abi_codegen/tool.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');

  final directoryInclude = packageRoot.resolve('engine/include/mixer_engine/');
  final directoryCpp = packageRoot.resolve('engine/source/abi/');

  final directoryDart = packageRoot.resolve('lib/mixer_engine/');

  generateAbiBridge(
    mode: GenerateMode.all,
    input: Input(
      files: Files(
        entrypointHeader: directoryInclude.resolve('mixer_engine_abi.h'),
        generatedCHeader: directoryInclude.resolve('structs.g.h'),
        generatedCpp: directoryCpp.resolve('structs.g.cpp'),
        generatedDart: directoryDart.resolve('mixer_engine.g.dart'),
        generatedDartStructs: directoryDart.resolve(
          'mixer_engine_structs.g.dart',
        ),
      ),
      options: InputOptions(
        preambleCHeader: trimIndent('''
          // AUTO-GENERATED BY `tool/abi_codegen.dart`.
          #pragma once
          
          // ReSharper disable once CppUnusedIncludeDirective
          #include <stdbool.h>
          #include <stddef.h>
          #include <stdint.h>

          #include "common.h"
        '''),

        preambleCpp: trimIndent('''
          // AUTO-GENERATED BY `tool/abi_codegen.dart`.

          #include "mixer_engine/structs.g.h"
          #include "util.h"
        '''),

        preambleDart: trimIndent('''
          // AUTO-GENERATED BY `tool/abi_codegen.dart`.

          // ignore_for_file: implicit_call_tearoffs, camel_case_extensions

          import 'dart:ffi';

          import 'package:ffi/ffi.dart';
          
          import 'converter_extensions.dart';
          import 'mixer_engine.g.dart';
        '''),

        abiExportMacroName: 'MIXER_ABI_EXPORT',

        renameStructInC: (name) => 'mixer_${name}_t',
        renameStructFreeFunction: (name) => 'mixer_free_$name',
        renameStructFreeFunctionInternal: (name) => 'internal_free_$name',
      ),
      structs: structs,
    ),
  );
}

final structs = <String, StructDefinition>{
  'AudioIOType': StructDefinition({
    'name': .string,
    'hasSeparateInputsAndOutputs': .bool,
    'inputDevices': .string.list,
    'outputDevices': .string.list,
  }),

  'AudioIOCombinationCapabilities': StructDefinition({
    'inputChannelNames': .string.list,
    'outputChannelNames': .string.list,
    'defaultBufferSize': .int,
    'availableSampleRates': .double.list,
    'availableBufferSizes': .int.list,
  }),

  'AudioIOSetup': StructDefinition({
    'ioType': .string,
    'inputDevice': .string,
    'outputDevice': .string,
    'sampleRate': .double,
    'bufferSize': .int,
  }),

  'AudioIOSetupInfo': StructDefinition({
    'setup': .struct('AudioIOSetup'),
    'capabilities': .struct('AudioIOCombinationCapabilities').nullable,
  }),

  'AudioIOOverview': StructDefinition({
    'availableIOTypes': .struct('AudioIOType').list,
  }),

  'GraphIONodeInfo': StructDefinition({
    'audioInputNodeID': .int,
    'audioOutputNodeID': .int,
  }),
};
