import 'dart:io';

import 'src/abi_codegen/generators/abi_generator.dart';
import 'src/abi_codegen/input.dart';
import 'src/abi_codegen/tool.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');

  final directoryInclude = packageRoot.resolve('engine/include/mixer_engine/');
  final directoryCpp = packageRoot.resolve('engine/source/abi/');

  final directoryDart = packageRoot.resolve('lib/mixer_engine/');

  generateAbiBridge(
    Input(
      files: Files(
        entrypointHeaderFile: directoryInclude.resolve('mixer_engine_abi.h'),
        generatedCHeaderFile: directoryInclude.resolve('generated_structs.h'),
        generatedCppFile: directoryCpp.resolve('generated_structs.cpp'),
        generatedDartFile: directoryDart.resolve('mixer_engine.g.dart'),
      ),
      options: InputOptions(
        preambleCHeader: trimIndent('''
          #pragma once

          #include "common.h"
        '''),

        preambleCpp: trimIndent('''
          #include "mixer_engine/mixer_engine_abi.h"
          #include "util.h"
        '''),

        preambleDart: trimIndent('''
          // Generated with `tool/abi_codegen.dart`.
          //
          // The first part of this file was internally generated by `package:ffigen`,
          // while the second part was generated with tools in the local codebase.

          import 'package:ffi/ffi.dart';
          
          import 'converter_extensions.dart';
        '''),

        abiExportMacroName: 'MIXER_ABI_EXPORT',

        renameStructInC: (name) => 'mixer_${name}_t',
        renameStructFreeFunction: (name) => 'mixer_free_$name',
        renameStructFreeFunctionInternal: (name) => 'internal_free_$name',
      ),
      structs: structs,
    ),
  );
}

final structs = <String, StructDefinition>{
  'AudioHostType': StructDefinition({
    'name': .string,
    'hasSeparateInputsAndOutputs': .bool,
    'inputDevices': .string.list,
    'outputDevices': .string.list,
  }),

  'AudioHostOverview': StructDefinition({
    'availableTypes': .struct('AudioHostType').list,
  }),
};
