import 'dart:io';

import 'src/abi_codegen/generators/abi_generator.dart';
import 'src/abi_codegen/input.dart';
import 'src/abi_codegen/tool.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');

  final directoryInclude = packageRoot.resolve('engine/include/mixer_engine/');
  final directoryCpp = packageRoot.resolve('engine/source/abi/');

  final directoryDart = packageRoot.resolve('lib/mixer_engine/');

  generateAbiBridge(
    mode: GenerateMode.all,
    input: Input(
      files: Files(
        entrypointHeader: directoryInclude.resolve('mixer_engine_abi.h'),
        generatedCHeader: directoryInclude.resolve('generated_structs.h'),
        generatedCpp: directoryCpp.resolve('generated_structs.cpp'),
        generatedDart: directoryDart.resolve('mixer_engine.g.dart'),
        generatedDartStructs: directoryDart.resolve(
          'mixer_engine_structs.g.dart',
        ),
      ),
      options: InputOptions(
        preambleCHeader: trimIndent('''
          #pragma once

          #include "common.h"
        '''),

        preambleCpp: trimIndent('''
          #include "mixer_engine/mixer_engine_abi.h"
          #include "util.h"
        '''),

        preambleDart: trimIndent('''
          // Generated by `tool/abi_codegen.dart`.

          // ignore_for_file: camel_case_extensions

          import 'dart:ffi';

          import 'package:ffi/ffi.dart';
          
          import 'converter_extensions.dart';
          import 'mixer_engine.g.dart';
        '''),

        abiExportMacroName: 'MIXER_ABI_EXPORT',

        renameStructInC: (name) => 'mixer_${name}_t',
        renameStructFreeFunction: (name) => 'mixer_free_$name',
        renameStructFreeFunctionInternal: (name) => 'internal_free_$name',
      ),
      structs: structs,
    ),
  );
}

final structs = <String, StructDefinition>{
  'AudioHostType': StructDefinition({
    'name': .string,
    'hasSeparateInputsAndOutputs': .bool,
    'inputDevices': .string.list,
    'outputDevices': .string.list,
  }),

  'AudioHostOverview': StructDefinition({
    'availableTypes': .struct('AudioHostType').list,
  }),
};
