// Generated by `tool/abi_codegen.dart`.

// ignore_for_file: camel_case_extensions

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import 'converter_extensions.dart';
import 'mixer_engine.g.dart';

typedef AudioHostType = ({
  String name,
  bool hasSeparateInputsAndOutputs,
  List<String> inputDevices,
  List<String> outputDevices,
});

extension AudioHostType_Mapping on mixer_AudioHostType_t {
  AudioHostType toDart() => (
    name: name.toDart(),
    hasSeparateInputsAndOutputs: hasSeparateInputsAndOutputs,
    inputDevices: inputDevices.toList(
      inputDevices_count,
      (p, i) => p[i].toDart(),
    ),
    outputDevices: outputDevices.toList(
      outputDevices_count,
      (p, i) => p[i].toDart(),
    ),
  );

  void assignFromDart(Arena arena, AudioHostType ref) => this
    ..name = ref.name.toUtf8(arena)
    ..hasSeparateInputsAndOutputs = ref.hasSeparateInputsAndOutputs
    ..inputDevices_count = ref.inputDevices.length
    ..inputDevices = ref.inputDevices.toUtf8Array(arena)
    ..outputDevices_count = ref.outputDevices.length
    ..outputDevices = ref.outputDevices.toUtf8Array(arena);
}

extension AudioHostType_toNative on AudioHostType {
  Pointer<mixer_AudioHostType_t> toNative(Arena arena) =>
      arena<mixer_AudioHostType_t>()..ref.assignFromDart(arena, this);
}

extension AudioHostType_free on Pointer<mixer_AudioHostType_t> {
  void free() => mixer_free_AudioHostType(this);
}

typedef AudioHostOverview = ({List<AudioHostType> availableTypes});

extension AudioHostOverview_Mapping on mixer_AudioHostOverview_t {
  AudioHostOverview toDart() => (
    availableTypes: availableTypes.toList(
      availableTypes_count,
      (p, i) => p[i].toDart(),
    ),
  );

  void assignFromDart(Arena arena, AudioHostOverview ref) => this
    ..availableTypes_count = ref.availableTypes.length
    ..availableTypes = ref.availableTypes.toNativeArray(
      arena<mixer_AudioHostType_t>,
      (p, i, e) => p[i].assignFromDart(arena, e),
    );
}

extension AudioHostOverview_toNative on AudioHostOverview {
  Pointer<mixer_AudioHostOverview_t> toNative(Arena arena) =>
      arena<mixer_AudioHostOverview_t>()..ref.assignFromDart(arena, this);
}

extension AudioHostOverview_free on Pointer<mixer_AudioHostOverview_t> {
  void free() => mixer_free_AudioHostOverview(this);
}
