// Generated with `tool/abi_codegen.dart`.
//
// The first part of this file was internally generated by `package:ffigen`,
// while the second part was generated with tools in the local codebase.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

import 'package:ffi/ffi.dart';

import 'converter_extensions.dart';

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_AudioHostType_t>)>()
external void mixer_free_AudioHostType(ffi.Pointer<mixer_AudioHostType_t> ref);

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_AudioHostOverview_t>)>()
external void mixer_free_AudioHostOverview(
  ffi.Pointer<mixer_AudioHostOverview_t> ref,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_error_t>)>()
external void mixer_error_free(ffi.Pointer<mixer_error_t> error);

@ffi.Native<ffi.Void Function()>()
external void mixer_initialize();

@ffi.Native<ffi.Void Function()>()
external void mixer_shutdown();

@ffi.Native<ffi.Pointer<engine_handle_t> Function()>()
external ffi.Pointer<engine_handle_t> mixer_engine_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<engine_handle_t>)>()
external void mixer_engine_destroy(ffi.Pointer<engine_handle_t> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_audio_host_setup_t>)>()
external void mixer_audio_host_setup_free(
  ffi.Pointer<mixer_audio_host_setup_t> ref,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mixer_audio_host_overview_t>)>()
external void mixer_audio_host_overview_free(
  ffi.Pointer<mixer_audio_host_overview_t> ref,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_overview_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_get_overview(
  ffi.Pointer<engine_handle_t> handle,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_overview_t>> out,
  ffi.Pointer<mixer_error_t> outError,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_reset(
  ffi.Pointer<engine_handle_t> handle,
  int numInputChannelsNeeded,
  int numOutputChannelsNeeded,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>> outSetup,
  ffi.Pointer<mixer_error_t> outError,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_switch_host_to(
  ffi.Pointer<engine_handle_t> handle,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>> outSetup,
  ffi.Pointer<mixer_error_t> outError,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_apply_input_device(
  ffi.Pointer<engine_handle_t> handle,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>> outSetup,
  ffi.Pointer<mixer_error_t> outError,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_apply_output_device(
  ffi.Pointer<engine_handle_t> handle,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>> outSetup,
  ffi.Pointer<mixer_error_t> outError,
);

@ffi.Native<
  mixer_call_result_t Function(
    ffi.Pointer<engine_handle_t>,
    ffi.Double,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>>,
    ffi.Pointer<mixer_error_t>,
  )
>()
external int mixer_audio_config_apply_quality_configuration(
  ffi.Pointer<engine_handle_t> handle,
  double sampleRate,
  int bufferSize,
  ffi.Pointer<ffi.Pointer<mixer_audio_host_setup_t>> outSetup,
  ffi.Pointer<mixer_error_t> outError,
);

final class mixer_AudioHostType_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Bool()
  external bool hasSeparateInputsAndOutputs;

  @ffi.Size()
  external int inputDevices_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> inputDevices;

  @ffi.Size()
  external int outputDevices_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> outputDevices;
}

final class mixer_AudioHostOverview_t extends ffi.Struct {
  @ffi.Size()
  external int availableTypes_count;

  external ffi.Pointer<mixer_AudioHostType_t> availableTypes;
}

typedef mixer_call_result_t = ffi.Int32;
typedef Dartmixer_call_result_t = int;
typedef mixer_error_t = ffi.Pointer<ffi.Char>;

final class engine_handle_t extends ffi.Opaque {}

final class mixer_audio_host_type_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Bool()
  external bool has_separate_inputs_and_outputs;

  @ffi.Size()
  external int input_device_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> input_devices;

  @ffi.Size()
  external int output_device_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> output_devices;
}

final class mixer_audio_host_setup_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> input_device;

  external ffi.Pointer<ffi.Char> output_device;

  @ffi.Double()
  external double sample_rate;

  @ffi.Int32()
  external int buffer_size;

  @ffi.Size()
  external int available_sample_rate_count;

  external ffi.Pointer<ffi.Double> available_sample_rates;

  @ffi.Size()
  external int available_buffer_size_count;

  external ffi.Pointer<ffi.Int32> available_buffer_sizes;
}

final class mixer_audio_host_overview_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> current_type;

  @ffi.Size()
  external int available_type_count;

  external ffi.Pointer<mixer_audio_host_type_t> available_types;

  external mixer_audio_host_setup_t current_setup;
}

const int MIXER_OK = 0;

const int MIXER_ERROR = 1;

const int MIXER_ERROR_INVALID_HANDLE = 2;

typedef AudioHostType = ({
  String name,
  bool hasSeparateInputsAndOutputs,
  List<String> inputDevices,
  List<String> outputDevices,
});

extension AudioHostType_toNative on AudioHostType {
  ffi.Pointer<mixer_AudioHostType_t> toNative(Arena arena) {
    final result = arena<mixer_AudioHostType_t>();
    result.ref
      ..name = name.toNative(arena)
      ..hasSeparateInputsAndOutputs = hasSeparateInputsAndOutputs
      ..inputDevices_count = inputDevices.length
      ..inputDevices = inputDevices.toNative((e) => e.toNative(arena))
      ..outputDevices_count = outputDevices.length
      ..outputDevices = outputDevices.toNative((e) => e.toNative(arena));
    return result;
  }
}

extension AudioHostType_toDart on mixer_AudioHostType_t {
  AudioHostType toDart() => (
    name: name.toDart(),
    hasSeparateInputsAndOutputs: hasSeparateInputsAndOutputs,
    inputDevices: inputDevices.toList(inputDevices_count, (e) => e.toDart()),
    outputDevices: outputDevices.toList(outputDevices_count, (e) => e.toDart()),
  );
}

extension AudioHostType_free on ffi.Pointer<mixer_AudioHostType_t> {
  void free() => mixer_free_AudioHostType(this);
}

typedef AudioHostOverview = ({List<AudioHostType> availableTypes});

extension AudioHostOverview_toNative on AudioHostOverview {
  ffi.Pointer<mixer_AudioHostOverview_t> toNative(Arena arena) {
    final result = arena<mixer_AudioHostOverview_t>();
    result.ref
      ..availableTypes_count = availableTypes.length
      ..availableTypes = availableTypes.toNative(
        arena<mixer_AudioHostType_t>,
        (e) => e
            .toNative(arena)
            .ref, // TODO: The Dart side needs a "populate struct" in addition to "allocate struct"
      );
    return result;
  }
}

extension AudioHostOverview_toDart on mixer_AudioHostOverview_t {
  AudioHostOverview toDart() => (
    availableTypes: availableTypes.toList(
      availableTypes_count,
      (e) => e.toDart(),
    ),
  );
}

extension AudioHostOverview_free on ffi.Pointer<mixer_AudioHostOverview_t> {
  void free() => mixer_free_AudioHostOverview(this);
}
